###
GET http://localhost:8080/need/date/param?date=2020-12-01 00:00:00
Accept: application/json

###
POST http://localhost:8080/need/date/user
Content-Type: application/json

{
  "id": "1",
  "name": "qinyi",
  "birthday": "2020/12/01"
}
